export const AREAS = [
    'Cilacap Selatan',
    'Cilacap Tengah',
    'Cilacap Utara',
    'Adipala',
    'Bantarsari',
    'Binangun',
    'Cimanggu',
    'Cipari',
    'Dayeuhluhur',
    'Gandrungmangu',
    'Jeruklegi',
    'Kampung Laut',
    'Karangpucung',
    'Kawunganten',
    'Kedungreja',
    'Kesugihan',
    'Kroya',
    'Majenang',
    'Maos',
    'Nusawungu',
    'Patimuan',
    'Sampang',
    'Sidareja',
    'Wanareja'
];
